"""
Real-data pipeline, Part 1: ingestion, cleaning, EDA and feature engineering.

Data source: Kaggle "Fraud Detection Dataset" (amanalisiddiqui), the public
PaySim synthetic-financial-transactions dataset (Lopez-Rojas, Elmir &
Axelsson, 2016). 6,362,620 real-schema transaction records; a reproducible
stratified 25% sample (1,590,656 rows, exact fraud rate preserved at
0.129%) is used here per project scope, generated by sample_real_data.py.

IMPORTANT SCOPE NOTE: PaySim provides transaction-level fields only. It has
no authentication, device/SIM-change, or customer-support-ticket data, so
this real-data pipeline REPLACES the synthetic transactions.csv analysis
(Milestone 2/3 Sections 5-6) but cannot replace the auth/device/ticket
analyses, which remain synthetic and are clearly labelled as such
throughout the accompanying report addendum.
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

BASE = Path(__file__).resolve().parents[1]
DATA = BASE / "data" / "real"
OUT = BASE / "outputs" / "real"
OUT.mkdir(parents=True, exist_ok=True)

log_lines = []


def log(msg):
    print(msg)
    log_lines.append(msg)


def load_and_clean():
    df = pd.read_csv(DATA / "paysim_quarter_sample.csv")
    n_before = len(df)

    n_dupes = df.duplicated().sum()
    df = df.drop_duplicates()
    n_nulls = int(df.isna().sum().sum())
    n_neg_amount = int((df["amount"] < 0).sum())
    df = df[df["amount"] >= 0]

    log(f"[quality-check] loaded {n_before} rows (25% stratified sample of 6,362,620-row source)")
    log(f"[quality-check] {n_dupes} duplicate rows removed; {n_nulls} null cells found")
    log(f"[quality-check] {n_neg_amount} negative-amount rows removed")
    log(f"[quality-check] final: {len(df)} rows, {df['isFraud'].sum()} fraud ({df['isFraud'].mean():.4%})")
    return df


def engineer_features(df):
    # classic PaySim balance-consistency error features (Lopez-Rojas et al., 2016)
    df = df.copy()
    df["errorBalanceOrig"] = df["newbalanceOrig"] + df["amount"] - df["oldbalanceOrg"]
    df["errorBalanceDest"] = df["oldbalanceDest"] + df["amount"] - df["newbalanceDest"]
    df["origEmptiedOut"] = ((df["oldbalanceOrg"] > 0) & (df["newbalanceOrig"] == 0)).astype(int)
    df["destStartedEmpty"] = (df["oldbalanceDest"] == 0).astype(int)
    df["amount_to_oldbalance_ratio"] = df["amount"] / df["oldbalanceOrg"].replace(0, np.nan)
    df["amount_to_oldbalance_ratio"] = df["amount_to_oldbalance_ratio"].fillna(0)
    df["is_transfer_or_cashout"] = df["type"].isin(["TRANSFER", "CASH_OUT"]).astype(int)
    df["type_TRANSFER"] = (df["type"] == "TRANSFER").astype(int)
    df["type_CASH_OUT"] = (df["type"] == "CASH_OUT").astype(int)
    df["type_PAYMENT"] = (df["type"] == "PAYMENT").astype(int)
    df["type_CASH_IN"] = (df["type"] == "CASH_IN").astype(int)
    df["type_DEBIT"] = (df["type"] == "DEBIT").astype(int)

    feature_cols = [
        "amount", "oldbalanceOrg", "newbalanceOrig", "oldbalanceDest", "newbalanceDest",
        "errorBalanceOrig", "errorBalanceDest", "origEmptiedOut", "destStartedEmpty",
        "amount_to_oldbalance_ratio", "type_TRANSFER", "type_CASH_OUT",
        "type_PAYMENT", "type_CASH_IN", "type_DEBIT", "step",
    ]
    log(f"[features] engineered {len(feature_cols)} transaction-level features "
        f"(incl. classic PaySim balance-error features)")
    return df, feature_cols


def make_eda_charts(df):
    fig, ax = plt.subplots(figsize=(5.5, 4))
    counts = df["type"].value_counts()
    fraud_rate = df.groupby("type")["isFraud"].mean().reindex(counts.index)
    colors = ["#C0504D" if r > 0 else "#2E5395" for r in fraud_rate]
    ax.bar(counts.index, counts.values, color=colors)
    ax.set_title("Real-data (PaySim quarter sample): transaction type volume\n(red = types where fraud occurs)")
    ax.set_ylabel("count")
    fig.tight_layout()
    fig.savefig(OUT / "chart_real_type_volume.png", dpi=130)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(5.5, 4))
    sub = df[df["type"].isin(["TRANSFER", "CASH_OUT"])]
    for lab, color, name in [(0, "#2E5395", "legitimate"), (1, "#C0504D", "fraud")]:
        vals = sub[sub["isFraud"] == lab]["amount"]
        ax.hist(np.log1p(vals), bins=40, alpha=0.6, label=name, color=color, density=True)
    ax.set_title("Real-data: transaction amount (log) by label\n(TRANSFER + CASH_OUT only, where fraud occurs)")
    ax.set_xlabel("log(1+amount)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(OUT / "chart_real_amount_by_label.png", dpi=130)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(5.5, 4))
    fraud = df[df["isFraud"] == 1]
    legit_sample = df[df["isFraud"] == 0].sample(n=min(20000, (df["isFraud"] == 0).sum()), random_state=42)
    ax.scatter(legit_sample["errorBalanceOrig"], legit_sample["errorBalanceDest"],
               s=6, alpha=0.15, color="#2E5395", label="legitimate (sample)")
    ax.scatter(fraud["errorBalanceOrig"], fraud["errorBalanceDest"],
               s=10, alpha=0.6, color="#C0504D", label="fraud")
    ax.set_xlabel("errorBalanceOrig")
    ax.set_ylabel("errorBalanceDest")
    ax.set_title("Real-data: balance-consistency errors by label")
    ax.legend()
    fig.tight_layout()
    fig.savefig(OUT / "chart_real_balance_error_scatter.png", dpi=130)
    plt.close(fig)
    log("[charts] saved 3 real-data baseline charts to outputs/real/")


def main():
    df = load_and_clean()
    df, feature_cols = engineer_features(df)
    make_eda_charts(df)

    df.to_csv(OUT / "real_transactions_engineered.csv", index=False)
    with open(OUT / "feature_cols.json", "w") as f:
        json.dump(feature_cols, f, indent=2)
    with open(OUT / "cleaning_log.txt", "w") as f:
        f.write("\n".join(log_lines))
    log("[done] real-data ingestion, cleaning and feature engineering complete.")


if __name__ == "__main__":
    main()
